### ISSUE TITLE
Possibly a simple documentation of the protocol to the "home server"

### ISSUE THREAD

**Issue by djmoonshine** [sebdehne/DehneEVSE-Firmware#1]
Hello

I'm just finishing a build of this EVSE charger. Thank you for this project.

Unfortunately I'm not that familiar with Kotlin and didn't manage to compile the code for it. Also I'm using other things as my "home server". So the question is would you be able to create a simple documentation of the communication  between the EVSE and the server? Then I would the be able to write something in a language that I'm more familiar with.

**Comment by sebdehne** [comment]
Hi, greate to hear you are re-building it.

Unfortunately I do not have the time/resource to write the documentation you need, but you I can give you some hints. The [firmware](https://github.com/sebdehne/DehneEVSE-Firmware/) basically uses raw bytes sent over TCP. 

It opens a TCP connection to the server to port [9091](https://github.com/sebdehne/DehneEVSE-Firmware/blob/master/src/smart_home_server_client.cpp#L68) and [sends the first message](https://github.com/sebdehne/DehneEVSE-Firmware/blob/master/src/smart_home_server_client.cpp#L76) which consist of 17 bytes. 1 byte for the firmware version and 16 for the serial number (to be able to distinguish multiple chargers). 

All the type of requests are listed here: https://github.com/sebdehne/DehneEVSE-Firmware/blob/master/src/smart_home_server_client.h#L12

There are only 2 "commands" which the server sends to the charger to controll the charging behaviour:
- REQUEST_TYPE_SET_PWM_PERCENT - adjusts the charge-rate
- RESPONSE_TYPE_SET_CONTACTOR_STATE - enables/disables the contactor

The other type of requests:
- REQUEST_TYPE_FIRMWARE - for firmware updates
- REQUEST_TYPE_COLLECT_DATA - request sent by the server to the charger to collect the current state

The client/charger will also send a "NOTIFY_TYPE_DATA_CHANGED" message to the server (which does not need to be responded to) when it detects some changes, for example when a cable is plugged in. The server then typically knowns that it needs to do a new data-collection cycle. I use this to in the web-app to show changes in real time using Websockets.

After the initial messae is sent, the client goes into listening mode: https://github.com/sebdehne/DehneEVSE-Firmware/blob/master/src/smart_home_server_client.cpp#L91

What you can see here in the code is that it reads the first byte which is the request-tye. After that, the messageLength is read which is 4 bytes (e.g. the header is 5 bytes). After that, the loop continues to read until it has receied all the bytes according to the messageLength. Once the entire request is read, the code prodeeds to handling.

And here can you find the code which handles each type of request which comes from the server to the charger (client): https://github.com/sebdehne/DehneEVSE-Firmware/blob/master/src/smart_home_server_client.cpp#L182

Hope this helps.

PS: The server needs to send a PING request regularly to keep the connection alive. Otherwise the charger/client will re-connect. See here: https://github.com/sebdehne/DehneEVSE-Firmware/blob/master/src/smart_home_server_client.cpp#L39

**Comment by Ralle001** [comment]
> Hello
> 
> I'm just finishing a build of this EVSE charger. Thank you for this project.
> 
> Unfortunately I'm not that familiar with Kotlin and didn't manage to compile the code for it. Also I'm using other things as my "home server". So the question is would you be able to create a simple documentation of the communication between the EVSE and the server? Then I would the be able to write something in a language that I'm more familiar with.

Did you manage to get it working?

**Comment by sebdehne** [comment]
There is also a [MQTT bridge](https://github.com/sebdehne/dehneevse-mqtt-bridge):

[EV stations] <--- TCP protocol as described above --> **MQTT-bridge** <---> [Your own software here]

**Comment by Ralle001** [comment]
Oh thats cool, I might do this, thank you

**Comment by djmoonshine** [comment]
> Unfortunately I'm not that familiar with Kotlin and didn't manage to compile the code for it. Also I'm using other things as my "home server". So the question is would you be able to create a simple documentation of the communication between the EVSE and the server? Then I would the be able to write something in a language that I'm more familiar with.

Yeah, kind of. But the project is on hold right now. But my use case was quite special since i really only needed the part for sending the correct PWM signal and also at below the normal duty cycle to initiate powerline communication to create a ISO15118 DC V2G charger.

**Comment by Ralle001** [comment]
I think most just wanna test it out or just kinda leave the Amps hardwired.

**Comment by sebdehne** [comment]
> I think most just wanna test it out or just kinda leave the Amps hardwired.

Probably yes, but then you loose the:
- ability to dynamically follow your solar production
- load sharing if you have multiple charging stations connected to the same circuit.
- manage the total power drawn dynamically; if you are billed by drawn power like me.

**Comment by Ralle001** [comment]
> 

Yeah you are right, but you could just mark which variables should be hardwired to test things. But of course the way you made this project it has more functions and options.
